### ISSUE TITLE
The Modernizr override breaks core javascript

### ISSUE THREAD

**Issue by NormySan** [oddhill/oddbaby-8#4]
Since some of the core modules javascript relies on the Modernizr library supplied by Drupal their code fails since Modernizr has not been included on the page when it should have.

Looking at the core Modernizr library definition it's included before any other scripts in the header:

``` yml
modernizr:
  # Block the page from being loaded until Modernizr is initialized.
  header: true
  remote: https://github.com/Modernizr/Modernizr
  license:
    name: MIT
    url: http://modernizr.com/license/
    gpl-compatible: true
  version: "v3.1.0"
  js:
    assets/vendor/modernizr/modernizr.min.js: { preprocess: 0, weight: -21, minified: true }
```

I'm not sure how to solve thos but Modernizr should preferably be included separately from the template javascript before any other javascript.

**Comment by jenslind** [comment]
Lets load modernizr from core for now. If we need to customize the build we should use `libraries-override` like this:

``` yaml
libraries-override:
  core/modernizr:
    js:
      assets/vendor/modernizr/modernizr.min.js: path_to_custom_build.js
```
